// This file is automatically generated by i18next-cli, because it was not existing. You can edit it based on your needs: https://www.i18next.com/overview/typescript#custom-type-options
import Resources from './i18n-resources';
import { defaultNS } from '../i18n';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: 'optimize'
    defaultNS: typeof defaultNS
    resources: {
      [defaultNS]: Resources
    }
  }
}
