// This file is automatically generated by i18next-cli. Do not edit manually.
type Resources = {
  experience: {
    perguntasQbPartTime: {
      content: {
        body: 'experience.perguntasQbPartTime.content.body',
        subtitle: 'experience.perguntasQbPartTime.content.subtitle',
        title: 'experience.perguntasQbPartTime.content.title',
      },
      timeline: {
        period: '2022',
        subtitle: 'PerguntasQB - Part-time',
        title: 'Mobile App Developer',
      },
    },
    qubItInternship: {
      content: {
        body: 'experience.qubItInternship.content.body',
        subtitle: 'experience.qubItInternship.content.subtitle',
        title: 'experience.qubItInternship.content.title',
      },
      timeline: {
        period: '2022',
        subTitle: 'qubIt - Part-time',
        title: 'Microservice development',
      },
    },
    tetrapiInternship: {
      content: {
        body: 'experience.tetrapiInternship.content.body',
        subtitle: 'experience.tetrapiInternship.content.subtitle',
        title: 'experience.tetrapiInternship.content.title',
      },
      timeline: {
        period: '2022',
        subtitle: 'Tetrapi Creative Solutions - Summer Internship',
        title: 'Prototype development',
      },
    },
    tetrapiJob: {
      content: {
        body: 'experience.tetrapiJob.content.body',
        subtitle: 'experience.tetrapiJob.content.subtitle',
        title: 'experience.tetrapiJob.content.title',
      },
      timeline: {
        period: '2022',
        subtitle: 'Tetrapi Creative Solutions',
        title: 'Fullstack developer & Project manager',
      },
    },
    university: {
      content: {
        body: 'experience.university.content.body',
        subtitle: 'experience.university.content.subtitle',
        title: 'experience.university.content.title',
      },
      timeline: {
        period: '2022',
        subtitle: 'Instituto Superior Técnico',
        title: 'Computer Science and Engineering Degree',
      },
    },
  },
  hero: {
    subtitle: 'Fullstack Developer',
    title: 'Hi! I\'m Pedro',
  },
};

export default Resources;
