// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "hero": {
    "subtitle": "Fullstack Developer",
    "title": "Hi! I'm Pedro"
  }
}

export default Resources;
